/* Applicant Profile Review enhancement */
(function(){
  RibacomApp.prototype.openApplicantProfile = async function(id){
    if(!['admin','super_admin'].includes(this.currentUser?.roleKey)) return this.toast('Administrator access required.','error');
    const {data:a,error}=await this.supabaseClient.from('membership_applications').select('*').eq('id',id).maybeSingle();
    if(error||!a) return this.toast(error?.message||'Application not found.','error');
    const esc2=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const field=(label,key)=>'<div class="bg-gray-50 rounded-xl p-3"><div class="text-[10px] uppercase font-bold text-gray-400">'+label+'</div><div class="text-sm font-semibold mt-1 break-words">'+esc2(a[key]||'—')+'</div></div>';
    const modal=document.createElement('div'); modal.id='ribacomApplicantProfile'; modal.className='fixed inset-0 z-[120] bg-black/70 flex items-center justify-center p-3';
    modal.innerHTML='<div class="bg-white rounded-3xl max-w-5xl w-full max-h-[94vh] overflow-y-auto p-5">'+
      '<div class="flex justify-between items-start gap-3 mb-5"><div><div class="text-[10px] uppercase tracking-widest font-black text-ribacom-green">RIBACOM Secretariat</div><h3 class="text-2xl font-extrabold text-ribacom-navy">Applicant Profile</h3><p class="text-xs text-gray-500">Complete membership application record.</p></div><button onclick="document.getElementById(\'ribacomApplicantProfile\')?.remove()" class="text-2xl">×</button></div>'+
      '<div class="flex flex-wrap gap-4 items-center mb-5"><div class="w-20 h-20 rounded-2xl bg-gray-100 overflow-hidden border">'+(a.photo_url?'<img src="'+esc2(a.photo_url)+'" class="w-full h-full object-cover">':'<div class="w-full h-full flex items-center justify-center text-gray-400"><i class="fa-solid fa-user text-2xl"></i></div>')+'</div><div><h4 class="text-xl font-extrabold">'+esc2(a.full_name)+'</h4><div class="text-xs text-gray-500">'+esc2(a.membership_category)+' • '+esc2(a.status)+'</div><div class="text-xs text-gray-500">'+esc2(a.email)+' • '+esc2(a.phone)+'</div></div></div>'+
      '<h4 class="font-extrabold text-ribacom-navy mb-2">Personal Information</h4><div class="grid md:grid-cols-3 gap-3 mb-5">'+field('Date of Birth','date_of_birth')+field('Gender','gender')+field('Nationality','nationality')+field('Place of Birth','place_of_birth')+field('State of Origin','state_of_origin')+field('LGA','lga')+field('Town / Village','town_village')+field('Community / Clan','community_clan')+field('Rivers / Bayelsa Connection','rivers_bayelsa_connection')+'</div>'+
      '<h4 class="font-extrabold text-ribacom-navy mb-2">Contact & Residence</h4><div class="grid md:grid-cols-2 gap-3 mb-5">'+field('Current Address','current_address')+field('Area / Location','area_location')+field('WhatsApp','whatsapp')+field('Preferred Contact','preferred_contact_method')+field('Date of Arrival in The Gambia','date_of_arrival_gambia')+field('Gambian Residence Permit','gambian_residence_permit_number')+'</div>'+
      '<h4 class="font-extrabold text-ribacom-navy mb-2">Family & Emergency</h4><div class="grid md:grid-cols-3 gap-3 mb-5">'+field('Father','father_name')+field('Mother','mother_name')+field('Spouse','spouse_name')+field('Next of Kin','next_of_kin_name')+field('Relationship','next_of_kin_relationship')+field('Next of Kin Phone','next_of_kin_phone')+field('Emergency Contact','emergency_contact_name')+field('Emergency Phone','emergency_contact_phone')+field('Medical Emergency Information','medical_emergency_information')+'</div>'+
      '<h4 class="font-extrabold text-ribacom-navy mb-2">Work & Identity</h4><div class="grid md:grid-cols-3 gap-3 mb-5">'+field('Occupation','occupation')+field('Employer / Business','employer_business')+field('Nigerian Passport Number','nigerian_passport_number')+field('National ID Number','national_id_number')+'</div>'+
      '<div class="bg-amber-50 border border-amber-200 rounded-2xl p-4 text-xs mb-5"><b>Declaration:</b> '+(a.declaration_accepted?'Accepted':'Not accepted')+' • Digital signature: '+esc2(a.digital_signature||'—')+'</div>'+
      '<div class="flex flex-wrap gap-2">'+(a.id_document_url?'<a target="_blank" href="'+esc2(a.id_document_url)+'" class="bg-gray-100 px-4 py-2 rounded-xl text-xs font-bold">View ID Document</a>':'')+(a.proof_of_nigerian_origin_url?'<a target="_blank" href="'+esc2(a.proof_of_nigerian_origin_url)+'" class="bg-gray-100 px-4 py-2 rounded-xl text-xs font-bold">Proof of Origin</a>':'')+(a.status==='pending'||a.status==='under_review'?'<button onclick="app.approveMembershipApplication(\''+esc2(a.id)+'\')" class="bg-ribacom-green text-white px-4 py-2 rounded-xl text-xs font-bold">Approve</button><button onclick="app.rejectMembershipApplication(\''+esc2(a.id)+'\')" class="bg-red-50 text-red-700 px-4 py-2 rounded-xl text-xs font-bold">Reject</button>':'')+'</div>'+
      '</div>';
    document.body.appendChild(modal);
  };
})();