/* D5 Admin Control extensions: About, Constitution, Gallery and full content navigation. */
(function(){
 const isAdmin=a=>String(a?.currentUser?.email||'').toLowerCase()==='iworimathomas@ymail.com' && a?.currentUser?.roleKey==='super_admin';
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const val=id=>document.getElementById(id)?.value?.trim()||'';
 const oldRender=RibacomApp.prototype.renderAdminDashboardView;
 RibacomApp.prototype.renderAdminDashboardView=function(){
   const base=oldRender.call(this);
   if(!isAdmin(this))return base;
   return base+`<div class="bg-white rounded-3xl p-5 card-shadow"><div class="flex flex-wrap gap-2"><button onclick="app.openAboutEditor()" class="bg-ribacom-navy text-white px-3 py-2 rounded-xl text-xs font-bold">About RIBACOM</button><button onclick="app.navigate('admin-constitution')" class="bg-ribacom-green text-white px-3 py-2 rounded-xl text-xs font-bold">Constitution</button><button onclick="app.navigate('admin-gallery')" class="bg-ribacom-gold text-ribacom-navy px-3 py-2 rounded-xl text-xs font-bold">Gallery</button><button onclick="app.navigate('admin-digital-ids')" class="bg-slate-800 text-white px-3 py-2 rounded-xl text-xs font-bold">Digital IDs</button></div></div>`;
 };
 const oldNav=RibacomApp.prototype.navigate;
 RibacomApp.prototype.navigate=function(viewId,params=null){
   if(viewId==='admin-constitution'){this.currentView=viewId;document.getElementById('appViewport').innerHTML=this.renderAdminConstitutionD5();this.updateAuthHeaderUI();return;}
   if(viewId==='admin-gallery'){this.currentView=viewId;document.getElementById('appViewport').innerHTML=this.renderAdminGalleryD5();this.updateAuthHeaderUI();return;}
   return oldNav.call(this,viewId,params);
 };
 RibacomApp.prototype.openAboutEditor=function(){
   if(!isAdmin(this))return;const a=this.db.about||{};
   const m=document.createElement('div');m.id='aboutEditor';m.className='fixed inset-0 z-[110] bg-black/50 flex items-center justify-center p-4';m.innerHTML=`<div class="bg-white rounded-3xl max-w-2xl w-full p-5 max-h-[92vh] overflow-y-auto"><h3 class="text-lg font-extrabold text-ribacom-navy mb-4">About RIBACOM</h3><div class="space-y-3">${[['org_name','Organisation name',a.name||'RIVERS BAYELSA COMMUNITY THE GAMBIA (RIBACOM)'],['motto','Motto',a.motto||'TRUTH • UNITY • SERVICE'],['contact_email','Contact email',a.contactEmail],['contact_phone','Contact phone',a.contactPhone],['address','Public contact address',a.address]].map(([id,l,v])=>`<label class="block text-xs font-bold">${l}<input id="ab_${id}" value="${esc(v)}" class="mt-1 w-full border rounded-xl px-3 py-2"></label>`).join('')}<label class="block text-xs font-bold">History<textarea id="ab_history" rows="4" class="mt-1 w-full border rounded-xl px-3 py-2">${esc(a.history)}</textarea></label><label class="block text-xs font-bold">Vision<textarea id="ab_vision" rows="3" class="mt-1 w-full border rounded-xl px-3 py-2">${esc(a.vision)}</textarea></label><label class="block text-xs font-bold">Mission<textarea id="ab_mission" rows="4" class="mt-1 w-full border rounded-xl px-3 py-2">${esc(a.mission)}</textarea></label><label class="block text-xs font-bold">Objectives (one per line)<textarea id="ab_objectives" rows="7" class="mt-1 w-full border rounded-xl px-3 py-2">${esc(Array.isArray(a.objectives)?a.objectives.join("\n"):(a.objectives||""))}</textarea></label><label class="block text-xs font-bold">Core Values (one per line)<textarea id="ab_core_values" rows="5" class="mt-1 w-full border rounded-xl px-3 py-2">${esc(Array.isArray(a.core_values)?a.core_values.join("\n"):(a.core_values||""))}</textarea></label></div><div class="flex gap-2 mt-4"><button onclick="app.saveAboutEditor()" class="flex-1 bg-ribacom-green text-white py-2.5 rounded-xl font-bold">Save</button><button onclick="document.getElementById('aboutEditor')?.remove()" class="px-5 bg-gray-100 rounded-xl font-bold">Cancel</button></div></div>`;document.body.appendChild(m);
 };
 RibacomApp.prototype.saveAboutEditor=async function(){if(!isAdmin(this))return;const payload={org_name:val('ab_org_name'),motto:val('ab_motto')||'TRUTH • UNITY • SERVICE',contact_email:val('ab_contact_email'),contact_phone:val('ab_contact_phone'),address:val('ab_address'),history:val('ab_history'),vision:val('ab_vision'),mission:val('ab_mission'),objectives:val('ab_objectives').split(/\n+/).map(x=>x.trim()).filter(Boolean),core_values:val('ab_core_values').split(/\n+/).map(x=>x.trim()).filter(Boolean),updated_at:new Date().toISOString(),updated_by:this.currentUser.id};const existing=(await this.supabaseClient.from('ribacom_about_content').select('id').limit(1)).data?.[0];const q=existing?this.supabaseClient.from('ribacom_about_content').update(payload).eq('id',existing.id):this.supabaseClient.from('ribacom_about_content').insert(payload);const {error}=await q;if(error)return this.toast(error.message,'error');document.getElementById('aboutEditor')?.remove();await this.loadCloudData();this.navigate('admin-dashboard');this.toast('About RIBACOM updated.','success');};
 RibacomApp.prototype.renderAdminGalleryD5=function(){if(!isAdmin(this))return '<div class="p-5">Administrator access required.</div>';const rows=this.db.gallery||[];return `<div class="space-y-5"><div class="bg-ribacom-navy text-white rounded-3xl p-5"><div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h2 class="text-xl font-extrabold">Gallery Management</h2><p class="text-xs text-gray-300">Upload photos from your phone, add descriptions and comments, publish or delete gallery items.</p></div><button onclick="app.openGalleryUploadD5()" class="bg-ribacom-gold text-ribacom-navy px-4 py-2.5 rounded-xl text-sm font-extrabold shadow hover:scale-[1.02] transition"><i class="fa-solid fa-cloud-arrow-up mr-1"></i> Upload Photo</button></div></div><div class="bg-white rounded-3xl p-4 overflow-x-auto"><table class="w-full text-xs"><thead><tr class="bg-gray-50"><th class="p-2 text-left">Title</th><th class="p-2 text-left">Caption</th><th class="p-2">Published</th><th class="p-2">Actions</th></tr></thead><tbody>${rows.map(x=>`<tr class="border-b"><td class="p-2 font-bold">${esc(x.title)}</td><td class="p-2">${esc(x.caption)}</td><td class="p-2">${x.is_published?'Yes':'No'}</td><td class="p-2 whitespace-nowrap"><button onclick="app.editGalleryD5('${x.id}')" class="text-blue-600 font-bold mr-2">Edit</button><button onclick="app.toggleGalleryD5('${x.id}',${!x.is_published})" class="text-emerald-600 font-bold mr-2">${x.is_published?'Unpublish':'Publish'}</button><button onclick="app.deleteAdminRecord('gallery','${x.id}')" class="text-red-600 font-bold">Delete</button></td></tr>`).join('')||'<tr><td colspan="4" class="p-6 text-center text-gray-500">No gallery records yet.</td></tr>'}</tbody></table></div><button onclick="app.navigate('admin-dashboard')" class="bg-ribacom-navy text-white px-4 py-2 rounded-xl text-xs font-bold">Back to Admin</button></div>`;};
 RibacomApp.prototype.openGalleryUploadD5=function(){
if(!isAdmin(this))return;
const m=document.createElement('div');m.id='galleryUpload';m.className='fixed inset-0 z-[110] bg-black/50 flex items-center justify-center p-4';
m.innerHTML='<div class="bg-white rounded-3xl max-w-lg w-full p-5 max-h-[92vh] overflow-y-auto"><h3 class="text-lg font-extrabold text-ribacom-navy">Upload Gallery Photos</h3><p class="text-xs text-gray-500 mt-1">Select multiple photos from your phone. Each photo can be up to 5 MB.</p><label class="block text-xs font-bold mt-4">Photos<input id="gu_file" type="file" accept="image/*" multiple class="mt-1 w-full border rounded-xl px-3 py-2 bg-white"></label><p id="gu_file_count" class="text-[11px] text-ribacom-green font-semibold mt-1">No photos selected</p><label class="block text-xs font-bold mt-3">Title<input id="gu_title" placeholder="e.g. RIBACOM General Meeting" class="mt-1 w-full border rounded-xl px-3 py-2"></label><label class="block text-xs font-bold mt-3">Comments / Notes<textarea id="gu_comments" rows="2" placeholder="Comments about these photos" class="mt-1 w-full border rounded-xl px-3 py-2"></textarea></label><label class="block text-xs font-bold mt-3">Description / Caption<textarea id="gu_caption" rows="3" placeholder="Description of these photos" class="mt-1 w-full border rounded-xl px-3 py-2"></textarea></label><label class="flex items-center gap-2 text-xs font-bold mt-3"><input id="gu_publish" type="checkbox" checked> Publish on the public Gallery</label><div class="flex gap-2 mt-4"><button id="gu_upload_btn" onclick="app.createGalleryD5()" class="flex-1 bg-ribacom-green text-white py-2.5 rounded-xl font-bold">Upload All Photos</button><button onclick="document.getElementById(\'galleryUpload\')?.remove()" class="px-5 bg-gray-100 rounded-xl font-bold">Cancel</button></div></div>';
document.body.appendChild(m);
document.getElementById('gu_file')?.addEventListener('change',function(){const n=this.files?.length||0;const el=document.getElementById('gu_file_count');if(el)el.textContent=n?String(n)+' photo'+(n===1?'':'s')+' selected':'No photos selected';});
};
RibacomApp.prototype.createGalleryD5=async function(){
if(!isAdmin(this))return;
const files=Array.from(document.getElementById('gu_file')?.files||[]);const title=val('gu_title');const caption=val('gu_caption');const comments=val('gu_comments');const published=!!document.getElementById('gu_publish')?.checked;
if(!files.length)return this.toast('Please choose one or more photos first.','warning');if(!title)return this.toast('Enter a photo title.','warning');
const invalid=files.find(f=>!f.type.startsWith('image/')||f.size>5*1024*1024);if(invalid)return this.toast('Each photo must be an image no larger than 5 MB. Problem file: '+invalid.name,'error');
const btn=document.getElementById('gu_upload_btn');if(btn){btn.disabled=true;btn.textContent='Uploading 0 of '+files.length+'...';}
let uploaded=0,failed=0;
for(const file of files){const id=crypto.randomUUID();const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const path='admin-media/gallery/'+id+'.'+ext;const {data,error}=await this.supabaseClient.storage.from('gallery').upload(path,file,{contentType:file.type,upsert:false,cacheControl:'3600'});
if(error){failed++;if(btn)btn.textContent='Uploading '+(uploaded+failed)+' of '+files.length+'...';continue;}
const image_url=this.supabaseClient.storage.from('gallery').getPublicUrl(data.path).data.publicUrl;const {error:insertError}=await this.supabaseClient.from('gallery').insert({id,title,caption,image_url,created_by:this.currentUser.id,submitted_by:this.currentUser.id,comments,is_published:published,approval_status:published?'approved':'pending',approved_by:published?this.currentUser.id:null,approved_at:published?new Date().toISOString():null});
if(insertError){await this.supabaseClient.storage.from('gallery').remove([path]);failed++;}else uploaded++;if(btn)btn.textContent='Uploading '+(uploaded+failed)+' of '+files.length+'...';}
document.getElementById('galleryUpload')?.remove();await this.loadCloudData();this.navigate('admin-gallery');this.toast(uploaded+' photo'+(uploaded===1?'':'s')+' uploaded'+(failed?'; '+failed+' failed':'')+'.',failed?'warning':'success');
};
RibacomApp.prototype.editGalleryD5=function(id){if(!isAdmin(this))return;const x=(this.db.gallery||[]).find(r=>r.id===id);if(!x)return;const m=document.createElement('div');m.id='galleryEditor';m.className='fixed inset-0 z-[110] bg-black/50 flex items-center justify-center p-4';m.innerHTML=`<div class="bg-white rounded-3xl max-w-lg w-full p-5"><h3 class="text-lg font-extrabold">Edit Gallery Item</h3><label class="block text-xs font-bold mt-3">Title<input id="ga_title" value="${esc(x.title)}" class="mt-1 w-full border rounded-xl px-3 py-2"></label><label class="block text-xs font-bold mt-3">Caption / Description<textarea id="ga_caption" rows="4" class="mt-1 w-full border rounded-xl px-3 py-2">${esc(x.caption)}</textarea></label><label class="block text-xs font-bold mt-3">Comments / Notes<textarea id="ga_comments" rows="3" class="mt-1 w-full border rounded-xl px-3 py-2">${esc(x.comments||"")}</textarea></label><label class="block text-xs font-bold mt-3">Upload image directly from phone<input id="ga_file" type="file" accept="image/*" class="mt-1 w-full border rounded-xl px-3 py-2 bg-white"></label><p class="text-[10px] text-gray-500 mt-1">Choose a photo from your mobile phone; the selected photo will replace the current photo automatically.</p><div class="flex gap-2 mt-4"><button onclick="app.saveGalleryD5('${id}')" class="flex-1 bg-ribacom-green text-white py-2.5 rounded-xl font-bold">Save</button><button onclick="document.getElementById('galleryEditor')?.remove()" class="px-5 bg-gray-100 rounded-xl font-bold">Cancel</button></div></div>`;document.body.appendChild(m);};
RibacomApp.prototype.saveGalleryD5=async function(id){if(!isAdmin(this))return;const x=(this.db.gallery||[]).find(r=>r.id===id);if(!x)return this.toast('Gallery item not found.','error');const p={title:val('ga_title'),caption:val('ga_caption'),comments:val('ga_comments'),image_url:x.image_url};const file=document.getElementById('ga_file')?.files?.[0];if(file){if(!file.type.startsWith('image/'))return this.toast('Please select an image file.','error');if(file.size>5*1024*1024)return this.toast('Photo must be 5 MB or smaller.','error');const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const path=`admin-media/gallery/${id}-${Date.now()}.${ext}`;const {data,error}=await this.supabaseClient.storage.from('gallery').upload(path,file,{contentType:file.type,upsert:true,cacheControl:'3600'});if(error)return this.toast(error.message,'error');p.image_url=this.supabaseClient.storage.from('gallery').getPublicUrl(data.path).data.publicUrl;}const {error}=await this.supabaseClient.from('gallery').update(p).eq('id',id);if(error)return this.toast(error.message,'error');document.getElementById('galleryEditor')?.remove();await this.loadCloudData();this.navigate('admin-gallery');this.toast('Gallery item updated.','success');};

})();
